import type { PayrollEntry, RefuerzoEntry } from "./types";

export const CCSS_RATE = 0.34;

export const PAYROLL_CATEGORY_ORDER = ["direccion", "foh", "boh"] as const;

/** Roles that are always in the "Gestión operativa" section, regardless of state */
export const MANAGEMENT_ROLE_IDS = new Set<string>(["DIR_OP", "CHEF_EJ"]);

export const CATEGORY_LABELS: Record<string, string> = {
  direccion: "Dirección y administración",
  foh: "Salón",
  boh: "Cocina",
};

export const DEFAULT_PAYROLL_ENTRIES: PayrollEntry[] = [
  // ── Gestión operativa (fuera del costo de equipo) ────────────────────────────
  {
    roleId: "DIR_OP",
    label: "Lisandro (dirección operativa)",
    category: "direccion",
    dependency: "fijo",
    isEssential: true,
    hasCCSS: false,
    isManagement: true,
    quantity: 1,
    netSalary: 3_000_000,
    elasticity: "ninguna",
    notes: "Socio operativo. Sin CCSS. Costo de gestión.",
  },
  {
    roleId: "CHEF_EJ",
    label: "Bruno Bonnao (chef ejecutivo)",
    category: "boh",
    dependency: "fijo",
    isEssential: true,
    hasCCSS: true,
    isManagement: true,
    quantity: 1,
    netSalary: 2_900_000,
    elasticity: "ninguna",
    notes: "Diseña y gestiona toda la carta. No depende de la demanda. Costo de gestión.",
  },
  // ── Dirección y administración ──────────────────────────────────────────────
  {
    roleId: "ADMIN",
    label: "Administrativo",
    category: "direccion",
    dependency: "fijo",
    isEssential: false,
    hasCCSS: true,
    quantity: 1,
    netSalary: 2_300_000,
    elasticity: "baja",
  },
  // ── Salón (FOH) ─────────────────────────────────────────────────────────────
  {
    roleId: "GERENTE",
    label: "Gerente",
    category: "foh",
    dependency: "fijo",
    isEssential: false,
    hasCCSS: true,
    quantity: 1,
    netSalary: 2_900_000,
    elasticity: "ninguna",
    notes: "Gestión integral del local.",
  },
  {
    roleId: "ENC_TURNO",
    label: "Encargado de turno",
    category: "foh",
    dependency: "fijo",
    isEssential: false,
    hasCCSS: true,
    quantity: 1,
    netSalary: 1_500_000,
    elasticity: "baja",
  },
  {
    roleId: "CAJERO",
    label: "Cajero",
    category: "foh",
    dependency: "fijo",
    isEssential: false,
    hasCCSS: true,
    quantity: 1,
    netSalary: 1_300_000,
    elasticity: "baja",
  },
  {
    roleId: "JEFE_SALON",
    label: "Jefe de salón",
    category: "foh",
    dependency: "demanda",
    isEssential: false,
    hasCCSS: true,
    quantity: 1,
    netSalary: 1_300_000,
    kitchenCoversThreshold: 2500,
    elasticity: "media",
    notes: "Se activa cuando la demanda de salón lo requiere.",
  },
  {
    roleId: "CAMARERO_AM",
    label: "Camareros AM",
    category: "foh",
    dependency: "demanda",
    isEssential: false,
    hasCCSS: true,
    quantity: 2,
    netSalary: 1_100_000,
    elasticity: "alta",
    notes: "Turno desayuno + almuerzo (9:00–17:00).",
  },
  {
    roleId: "CAMARERO_PM",
    label: "Camareros PM",
    category: "foh",
    dependency: "demanda",
    isEssential: false,
    hasCCSS: true,
    quantity: 2,
    netSalary: 1_100_000,
    elasticity: "alta",
    notes: "Turno merienda + cena (17:00–cierre).",
  },
  {
    roleId: "RUNNER_COMIS",
    label: "Runner / Comis",
    category: "foh",
    dependency: "demanda",
    isEssential: false,
    hasCCSS: true,
    quantity: 1,
    netSalary: 550_000,
    kitchenCoversThreshold: 1200,
    elasticity: "alta",
    notes: "Soporte de sala. Puede ser eventual.",
  },
  {
    roleId: "BARRA_BARISTA",
    label: "Barra / Barista",
    category: "foh",
    dependency: "demanda",
    isEssential: false,
    hasCCSS: true,
    quantity: 2,
    netSalary: 1_400_000,
    elasticity: "media",
    notes: "Diurno desde apertura.",
  },
  // ── Cocina (BOH) ─────────────────────────────────────────────────────────────
  {
    roleId: "JEFE_COCINA",
    label: "Jefe de cocina",
    category: "boh",
    dependency: "fijo",
    isEssential: false,
    hasCCSS: true,
    quantity: 1,
    netSalary: 2_000_000,
    elasticity: "baja",
    notes: "Operación diaria de cocina. Mínimo 1 desde la apertura.",
  },
  {
    roleId: "PROD_AM",
    label: "Producción AM (cocina fría / mise en place)",
    category: "boh",
    dependency: "fijo",
    isEssential: true,
    hasCCSS: true,
    quantity: 1,
    netSalary: 1_095_000,
    elasticity: "ninguna",
    notes: "Presente desde la apertura. No depende de la demanda.",
  },
  {
    roleId: "AYUDANTE_COC_AM",
    label: "Ayudante de cocina AM (despacho)",
    category: "boh",
    dependency: "demanda",
    isEssential: false,
    hasCCSS: true,
    quantity: 1,
    netSalary: 1_095_000,
    elasticity: "media",
    notes: "Se activa a partir de ~100 cubiertos pico mañana.",
  },
  {
    roleId: "AYUDANTE_COC_PM",
    label: "Ayudante de cocina PM (despacho)",
    category: "boh",
    dependency: "demanda",
    isEssential: false,
    hasCCSS: true,
    quantity: 1,
    netSalary: 1_095_000,
    elasticity: "media",
    notes: "Se activa según demanda vespertina.",
  },
  {
    roleId: "BACHA",
    label: "Bacha",
    category: "boh",
    dependency: "demanda",
    isEssential: false,
    hasCCSS: true,
    quantity: 1,
    netSalary: 1_095_000,
    kitchenCoversThreshold: 500,
    kitchenCoversPerPerson: 1200,
    elasticity: "alta",
    notes: "Más elástico. Escala con el volumen de servicio.",
  },
];

export const DEFAULT_REFUERZOS: RefuerzoEntry[] = [
  { label: "Runner / Comis", valor4hs: 60_000 },
  { label: "Refuerzo Barra / Barista", valor4hs: 60_000 },
];
